/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/coremodule/core.module';
import * as i2 from '../../../app/services/authentication.service';
import * as i3 from '@angular/http';
import * as i4 from '../../../app/services/articles.service';
export const CoreModuleNgFactory:i0.NgModuleFactory<i1.CoreModule> = i0.ɵcmf(i1.CoreModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.AuthenticationService,i2.AuthenticationService,[i3.Http]),i0.ɵmpd(4608,
          i4.ArticlesService,i4.ArticlesService,[i3.Http]),i0.ɵmpd(512,i1.CoreModule,
          i1.CoreModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvY29yZW1vZHVsZS9jb3JlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL2NvcmVtb2R1bGUvY29yZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
