/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../app/route-study/product/detail/item/item.component';
const styles_ItemComponent:any[] = ([] as any[]);
export const RenderType_ItemComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ItemComponent,data:{}});
export function View_ItemComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['The route is "product/detail/item".'])),
      (_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(null as any));
}
export function View_ItemComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-product-detail-item',
      ([] as any[]),(null as any),(null as any),(null as any),View_ItemComponent_0,
      RenderType_ItemComponent)),i0.ɵdid(49152,(null as any),0,i1.ItemComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const ItemComponentNgFactory:i0.ComponentFactory<i1.ItemComponent> = i0.ɵccf('my-product-detail-item',
    i1.ItemComponent,View_ItemComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbS9pdGVtLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvZGV0YWlsL2l0ZW0vaXRlbS5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvZGV0YWlsL2l0ZW0vaXRlbS5jb21wb25lbnQudHMuSXRlbUNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9wcm9kdWN0L2RldGFpbC9pdGVtL2l0ZW0uY29tcG9uZW50LnRzLkl0ZW1Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2PlRoZSByb3V0ZSBpcyBcInByb2R1Y3QvZGV0YWlsL2l0ZW1cIi48L2Rpdj5cbiAgIiwiPG15LXByb2R1Y3QtZGV0YWlsLWl0ZW0+PC9teS1wcm9kdWN0LWRldGFpbC1pdGVtPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNJO01BQUE7TUFBQSw4QkFBSztNQUF5Qzs7O29CQ0RsRDtNQUFBOzhCQUFBLFVBQUE7TUFBQTs7OyJ9
