/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../app/route-study/product/detail/item/item.module';
import * as i2 from './item.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '../../../../../../app/route-study/product/detail/item/item.router.module';
import * as i5 from '../../../../../../app/route-study/product/detail/item/item.component';
export const ItemModuleNgFactory:i0.NgModuleFactory<i1.ItemModule> = i0.ɵcmf(i1.ItemModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ItemComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i4.ItemRouterModule,i4.ItemRouterModule,([] as any[])),i0.ɵmpd(512,i1.ItemModule,
              i1.ItemModule,([] as any[])),i0.ɵmpd(1024,i3.ROUTES,() => {
            return [[{path:'',component:i5.ItemComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbS9pdGVtLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvZGV0YWlsL2l0ZW0vaXRlbS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
