/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../app/route-study/product/detail/item2/item2.component';
import * as i2 from '../../../../../../app/route-study/product/test.service';
const styles_Item2Component:any[] = ([] as any[]);
export const RenderType_Item2Component:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Item2Component,data:{}});
export function View_Item2Component_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['The route is "product/detail/item2".'])),
      (_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(null as any));
}
export function View_Item2Component_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-product-detail-item2',
      ([] as any[]),(null as any),(null as any),(null as any),View_Item2Component_0,
      RenderType_Item2Component)),i0.ɵdid(49152,(null as any),0,i1.Item2Component,
      [i2.TestService],(null as any),(null as any))],(null as any),(null as any));
}
export const Item2ComponentNgFactory:i0.ComponentFactory<i1.Item2Component> = i0.ɵccf('my-product-detail-item2',
    i1.Item2Component,View_Item2Component_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbTIvaXRlbTIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbTIvaXRlbTIuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9wcm9kdWN0L2RldGFpbC9pdGVtMi9pdGVtMi5jb21wb25lbnQudHMuSXRlbTJDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbTIvaXRlbTIuY29tcG9uZW50LnRzLkl0ZW0yQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdj5UaGUgcm91dGUgaXMgXCJwcm9kdWN0L2RldGFpbC9pdGVtMlwiLjwvZGl2PlxuICAiLCI8bXktcHJvZHVjdC1kZXRhaWwtaXRlbTI+PC9teS1wcm9kdWN0LWRldGFpbC1pdGVtMj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsMkNBQ0k7TUFBQTtNQUFBLDhCQUFLO01BQTBDOzs7b0JDRG5EO01BQUE7K0JBQUEsVUFBQTtNQUFBOzs7In0=
