/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../app/route-study/product/detail/item2/item2.module';
import * as i2 from './item2.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '../../../../../../app/route-study/product/detail/item2/item2.router.module';
import * as i5 from '../../../../../../app/route-study/product/detail/item2/item2.component';
export const Item2ModuleNgFactory:i0.NgModuleFactory<i1.Item2Module> = i0.ɵcmf(i1.Item2Module,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.Item2ComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i4.Item2RouterModule,i4.Item2RouterModule,([] as any[])),i0.ɵmpd(512,
              i1.Item2Module,i1.Item2Module,([] as any[])),i0.ɵmpd(1024,i3.ROUTES,
              () => {
                return [[{path:'',component:i5.Item2Component}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbTIvaXRlbTIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbTIvaXRlbTIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
