/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../../app/route-study/product/detail/item2/item2.router.module';
import * as i2 from './item2.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '../../../../../../app/route-study/product/detail/item2/item2.component';
export const Item2RouterModuleNgFactory:i0.NgModuleFactory<i1.Item2RouterModule> = i0.ɵcmf(i1.Item2RouterModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.Item2ComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i1.Item2RouterModule,i1.Item2RouterModule,([] as any[])),i0.ɵmpd(1024,
              i3.ROUTES,() => {
                return [[{path:'',component:i4.Item2Component}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvaXRlbTIvaXRlbTIucm91dGVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvZGV0YWlsL2l0ZW0yL2l0ZW0yLnJvdXRlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
