/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from '../../../../app/articles/edit/edit.component';
export declare const RenderType_EditComponent: i0.RendererType2;
export declare function View_EditComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_EditComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const EditComponentNgFactory: i0.ComponentFactory<i1.EditComponent>;
