/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/authentication/authentication-routing.module';
import * as i2 from './authentication.component.ngfactory';
import * as i3 from './signin/signin.component.ngfactory';
import * as i4 from './signup/signup.component.ngfactory';
import * as i5 from '@angular/router';
import * as i6 from '../../../app/authentication/authentication.component';
import * as i7 from '../../../app/authentication/signin/signin.component';
import * as i8 from '../../../app/authentication/signup/signup.component';
export const AuthenticationRoutingModuleNgFactory:i0.NgModuleFactory<i1.AuthenticationRoutingModule> = i0.ɵcmf(i1.AuthenticationRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AuthenticationComponentNgFactory,i3.SigninComponentNgFactory,i4.SignupComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,i5.RouterModule,
          i5.RouterModule,[[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i1.AuthenticationRoutingModule,
          i1.AuthenticationRoutingModule,([] as any[])),i0.ɵmpd(1024,i5.ROUTES,() => {
        return [[{path:'authentication',component:i6.AuthenticationComponent,children:[{path:'signin',
            component:i7.SigninComponent},{path:'signup',component:i8.SignupComponent}]}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXV0aGVudGljYXRpb24vYXV0aGVudGljYXRpb24tcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9hdXRoZW50aWNhdGlvbi9hdXRoZW50aWNhdGlvbi1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
