/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '../../../app/authentication/authentication.component';
import * as i3 from '../../../app/authentication/logger.service';
const styles_AuthenticationComponent:any[] = ([] as any[]);
export const RenderType_AuthenticationComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AuthenticationComponent,data:{}});
export function View_AuthenticationComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),13,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      1,'a',[['href','/api/oauth/google']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Sign in with Google'])),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'a',[['href','/api/oauth/facebook']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Sign in with Facebook'])),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'a',[['href','/api/oauth/twitter']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Sign in with Twitter'])),
      (_l()(),i0.ɵted((null as any),['\n  '])),(_l()(),i0.ɵeld(16777216,(null as any),
          (null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),i0.ɵdid(212992,(null as any),
          0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,i0.ComponentFactoryResolver,
              [8,(null as any)],i0.ChangeDetectorRef],(null as any),(null as any)),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        _ck(_v,12,0);
      },(null as any));
}
export function View_AuthenticationComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'authentication',
      ([] as any[]),(null as any),(null as any),(null as any),View_AuthenticationComponent_0,
      RenderType_AuthenticationComponent)),i0.ɵdid(49152,(null as any),0,i2.AuthenticationComponent,
      [i3.LoggerService],(null as any),(null as any))],(null as any),(null as any));
}
export const AuthenticationComponentNgFactory:i0.ComponentFactory<i2.AuthenticationComponent> = i0.ɵccf('authentication',
    i2.AuthenticationComponent,View_AuthenticationComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXV0aGVudGljYXRpb24vYXV0aGVudGljYXRpb24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXV0aGVudGljYXRpb24vYXV0aGVudGljYXRpb24uY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9hdXRoZW50aWNhdGlvbi9hdXRoZW50aWNhdGlvbi5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXV0aGVudGljYXRpb24vYXV0aGVudGljYXRpb24uY29tcG9uZW50LnRzLkF1dGhlbnRpY2F0aW9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdj5cbiAgPGEgaHJlZj1cIi9hcGkvb2F1dGgvZ29vZ2xlXCI+U2lnbiBpbiB3aXRoIEdvb2dsZTwvYT5cbiAgPGEgaHJlZj1cIi9hcGkvb2F1dGgvZmFjZWJvb2tcIj5TaWduIGluIHdpdGggRmFjZWJvb2s8L2E+XG4gIDxhIGhyZWY9XCIvYXBpL29hdXRoL3R3aXR0ZXJcIj5TaWduIGluIHdpdGggVHdpdHRlcjwvYT5cbiAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuPC9kaXY+XG4iLCI8YXV0aGVudGljYXRpb24+PC9hdXRoZW50aWNhdGlvbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUs7YUFBQSwwQkFDSDtNQUFBO01BQUEsOEJBQTRCO01BQXVCLHlDQUNuRDtVQUFBO1VBQUEsOEJBQThCO01BQXlCLHlDQUN2RDtVQUFBO1VBQUEsOEJBQTZCO01BQXdCLHlDQUNyRDtVQUFBO1VBQUEsbURBQUE7VUFBQTtjQUFBO01BQStCLHVDQUMzQjs7UUFESjs7OztvQkNKRjtNQUFBO3dDQUFBLFVBQUE7TUFBQTs7OyJ9
