/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i2 from '../../../app/authentication/authentication.component';
export declare const RenderType_AuthenticationComponent: i0.RendererType2;
export declare function View_AuthenticationComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_AuthenticationComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const AuthenticationComponentNgFactory: i0.ComponentFactory<i2.AuthenticationComponent>;
