/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/authentication/authentication.module';
import * as i2 from './authentication.component.ngfactory';
import * as i3 from './signin/signin.component.ngfactory';
import * as i4 from './signup/signup.component.ngfactory';
import * as i5 from '@angular/common';
import * as i6 from '@angular/forms';
import * as i7 from '../../../app/authentication/logger.service';
import * as i8 from '@angular/router';
import * as i9 from '../../../app/authentication/authentication-routing.module';
import * as i10 from '../../../app/authentication/authentication.component';
import * as i11 from '../../../app/authentication/signin/signin.component';
import * as i12 from '../../../app/authentication/signup/signup.component';
export const AuthenticationModuleNgFactory:i0.NgModuleFactory<i1.AuthenticationModule> = i0.ɵcmf(i1.AuthenticationModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AuthenticationComponentNgFactory,i3.SigninComponentNgFactory,i4.SignupComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.NgLocalization,
          i5.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i6.ɵi,i6.ɵi,([] as any[])),
          i0.ɵmpd(4608,i7.LoggerService,i7.LoggerService,([] as any[])),i0.ɵmpd(512,
              i5.CommonModule,i5.CommonModule,([] as any[])),i0.ɵmpd(512,i6.ɵba,i6.ɵba,
              ([] as any[])),i0.ɵmpd(512,i6.FormsModule,i6.FormsModule,([] as any[])),
          i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],[2,i8.Router]]),i0.ɵmpd(512,
              i9.AuthenticationRoutingModule,i9.AuthenticationRoutingModule,([] as any[])),
          i0.ɵmpd(512,i1.AuthenticationModule,i1.AuthenticationModule,([] as any[])),
          i0.ɵmpd(1024,i8.ROUTES,() => {
            return [[{path:'authentication',component:i10.AuthenticationComponent,
                children:[{path:'signin',component:i11.SigninComponent},{path:'signup',
                    component:i12.SignupComponent}]}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXV0aGVudGljYXRpb24vYXV0aGVudGljYXRpb24ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXV0aGVudGljYXRpb24vYXV0aGVudGljYXRpb24ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
