/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../app/route-study/product/detail/detail.router.module';
import * as i2 from './detail.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '../../../../../app/route-study/product/detail/detail.component';
export const DetailRouterModuleNgFactory:i0.NgModuleFactory<i1.DetailRouterModule> = i0.ɵcmf(i1.DetailRouterModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.DetailComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i1.DetailRouterModule,i1.DetailRouterModule,([] as any[])),i0.ɵmpd(1024,
              i3.ROUTES,() => {
                return [[{path:'item',loadChildren:'./item/item.module#ItemModule'},
                    {path:'',component:i4.DetailComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvZGV0YWlsLnJvdXRlci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9wcm9kdWN0L2RldGFpbC9kZXRhaWwucm91dGVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
