/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '../../../../../app/route-study/product/detail/detail.component';
const styles_DetailComponent:any[] = ([] as any[]);
export const RenderType_DetailComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_DetailComponent,data:{}});
export function View_DetailComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['The route is "product/detail".'])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'div',[['style','background:green']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n       '])),
      (_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',[['name',
          'detail']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,'detail'],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n  ']))],(_ck,_v) => {
    _ck(_v,7,0);
  },(null as any));
}
export function View_DetailComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-product-detail',
      ([] as any[]),(null as any),(null as any),(null as any),View_DetailComponent_0,
      RenderType_DetailComponent)),i0.ɵdid(49152,(null as any),0,i2.DetailComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const DetailComponentNgFactory:i0.ComponentFactory<i2.DetailComponent> = i0.ɵccf('my-product-detail',
    i2.DetailComponent,View_DetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9kZXRhaWwvZGV0YWlsLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvZGV0YWlsL2RldGFpbC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvZGV0YWlsL2RldGFpbC5jb21wb25lbnQudHMuRGV0YWlsQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvZGV0YWlsL2RldGFpbC5jb21wb25lbnQudHMuRGV0YWlsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGRpdj5UaGUgcm91dGUgaXMgXCJwcm9kdWN0L2RldGFpbFwiLjwvZGl2PlxuICAgIDxkaXYgc3R5bGU9XCJiYWNrZ3JvdW5kOmdyZWVuXCI+XG4gICAgICAgPHJvdXRlci1vdXRsZXQgbmFtZT1cImRldGFpbFwiPjwvcm91dGVyLW91dGxldD5cbiAgICA8L2Rpdj5cbiAgIiwiPG15LXByb2R1Y3QtZGV0YWlsPjwvbXktcHJvZHVjdC1kZXRhaWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNJO01BQUE7TUFBQSw4QkFBSztNQUFvQywyQ0FDekM7VUFBQTtVQUFBLDhCQUE4QjtNQUMzQjtVQUFBO2FBQUE7c0NBQUE7VUFBQSxlQUE2QywyQ0FDMUM7VUFBQTtJQURIOzs7O29CQ0hQO01BQUE7Z0NBQUEsVUFBQTtNQUFBOzs7In0=
