/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/route-study/route-study.module';
import * as i2 from './route-study.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/platform-browser';
import * as i5 from '@angular/router';
import * as i6 from '../../../app/route-study/route-study-routing.module';
import * as i7 from '../../../app/route-study/route-study.component';
export const RouteStudyModuleNgFactory:i0.NgModuleFactory<i1.RouteStudyModule> = i0.ɵcmf(i1.RouteStudyModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.RouteStudyComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i3.NgLocalization,
              i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
              i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i4.DomSanitizer,i4.ɵe,[i3.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i4.DomSanitizer]),i0.ɵmpd(4608,
              i4.HAMMER_GESTURE_CONFIG,i4.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i4.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i4.ɵDomEventsPlugin(p0_0),new i4.ɵKeyEventsPlugin(p1_0),
                    new i4.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i3.DOCUMENT,i3.DOCUMENT,i3.DOCUMENT,i4.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i4.EventManager,i4.EventManager,[i4.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i4.ɵDomSharedStylesHost,i4.ɵDomSharedStylesHost,[i3.DOCUMENT]),
          i0.ɵmpd(4608,i4.ɵDomRendererFactory2,i4.ɵDomRendererFactory2,[i4.EventManager,
              i4.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i4.ɵDomRendererFactory2]),i0.ɵmpd(6144,i4.ɵSharedStylesHost,(null as any),
              [i4.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i4.Meta,i4.Meta,[i3.DOCUMENT]),i0.ɵmpd(4608,
              i4.Title,i4.Title,[i3.DOCUMENT]),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i4.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any) => {
                return [i4.ɵc(p0_0,p0_1)];
              },[[2,i4.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i4.BrowserModule,i4.BrowserModule,[[3,i4.BrowserModule]]),i0.ɵmpd(512,
              i5.RouterModule,i5.RouterModule,[[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,
              i6.RouteStudyRoutingModule,i6.RouteStudyRoutingModule,([] as any[])),
          i0.ɵmpd(512,i1.RouteStudyModule,i1.RouteStudyModule,([] as any[])),i0.ɵmpd(1024,
              i5.ROUTES,() => {
                return [[{path:'route-study',component:i7.RouteStudyComponent,children:[{path:'rshome',
                    loadChildren:'./rshome/rshome.module#RSHomeModule'},{path:'product',
                    loadChildren:'./product/product.module#ProductModule'}]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcm91dGUtc3R1ZHkubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcm91dGUtc3R1ZHkubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
