/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/route-study/route-study-routing.module';
import * as i2 from './route-study.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '../../../app/route-study/route-study.component';
export const RouteStudyRoutingModuleNgFactory:i0.NgModuleFactory<i1.RouteStudyRoutingModule> = i0.ɵcmf(i1.RouteStudyRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.RouteStudyComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i1.RouteStudyRoutingModule,i1.RouteStudyRoutingModule,([] as any[])),
          i0.ɵmpd(1024,i3.ROUTES,() => {
            return [[{path:'route-study',component:i4.RouteStudyComponent,children:[{path:'rshome',
                loadChildren:'./rshome/rshome.module#RSHomeModule'},{path:'product',
                loadChildren:'./product/product.module#ProductModule'}]}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcm91dGUtc3R1ZHktcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9yb3V0ZS1zdHVkeS1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
