/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i3 from '../../../app/route-study/route-study.component';
export declare const RenderType_RouteStudyComponent: i0.RendererType2;
export declare function View_RouteStudyComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_RouteStudyComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const RouteStudyComponentNgFactory: i0.ComponentFactory<i3.RouteStudyComponent>;
