/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '../../../../app/route-study/product/product.component';
const styles_ProductComponent:any[] = ([] as any[]);
export const RenderType_ProductComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ProductComponent,data:{}});
export function View_ProductComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['The route is "product".'])),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          4,'div',[['style','background:red']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n       '])),
      (_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['style',
          'background:blue']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n       '])),(_l()(),i0.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',[['name','product']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(212992,
          (null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
              i0.ComponentFactoryResolver,[8,'product'],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),
          ['\n  ']))],(_ck,_v) => {
    _ck(_v,7,0);
    _ck(_v,13,0);
  },(null as any));
}
export function View_ProductComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-product',([] as any[]),
      (null as any),(null as any),(null as any),View_ProductComponent_0,RenderType_ProductComponent)),
      i0.ɵdid(49152,(null as any),0,i2.ProductComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ProductComponentNgFactory:i0.ComponentFactory<i2.ProductComponent> = i0.ɵccf('my-product',
    i2.ProductComponent,View_ProductComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9wcm9kdWN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvcHJvZHVjdC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvcHJvZHVjdC5jb21wb25lbnQudHMuUHJvZHVjdENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9wcm9kdWN0L3Byb2R1Y3QuY29tcG9uZW50LnRzLlByb2R1Y3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2PlRoZSByb3V0ZSBpcyBcInByb2R1Y3RcIi48L2Rpdj5cbiAgICA8ZGl2IHN0eWxlPVwiYmFja2dyb3VuZDpyZWRcIj5cbiAgICAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBzdHlsZT1cImJhY2tncm91bmQ6Ymx1ZVwiPlxuICAgICAgIDxyb3V0ZXItb3V0bGV0IG5hbWU9XCJwcm9kdWN0XCI+PC9yb3V0ZXItb3V0bGV0PlxuICAgIDwvZGl2PlxuICAiLCI8bXktcHJvZHVjdD48L215LXByb2R1Y3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNJO01BQUE7TUFBQSw4QkFBSztNQUE2QiwyQ0FDbEM7VUFBQTtVQUFBLDhCQUE0QjtNQUN6QjtVQUFBO2FBQUE7c0NBQUE7VUFBQSxlQUErQiwyQ0FDNUI7VUFBQSxhQUNOO1VBQUE7VUFBQSxnQkFBNkIsOENBQzFCO1VBQUE7VUFBQSxpRUFBQTtVQUFBOzBDQUFBO1VBQUEsZUFBOEMsMkNBQzNDO1VBQUE7SUFKSDtJQUdBOzs7O29CQ05QO01BQUE7YUFBQTtVQUFBOzs7In0=
