/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../app/route-study/product/product.module';
import * as i2 from './product.component.ngfactory';
import * as i3 from '../../../../app/route-study/product/test.service';
import * as i4 from '@angular/router';
import * as i5 from '../../../../app/route-study/product/product.router.module';
import * as i6 from '../../../../app/route-study/product/product.component';
export const ProductModuleNgFactory:i0.NgModuleFactory<i1.ProductModule> = i0.ɵcmf(i1.ProductModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ProductComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.TestService,i3.TestService,([] as any[])),i0.ɵmpd(512,i4.RouterModule,
              i4.RouterModule,[[2,i4.ɵa],[2,i4.Router]]),i0.ɵmpd(512,i5.ProductRouterModule,
              i5.ProductRouterModule,([] as any[])),i0.ɵmpd(512,i1.ProductModule,i1.ProductModule,
              ([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'list',component:i6.ProductComponent,loadChildren:'./list/list.module#ListModule'},
                {path:'detail',component:i6.ProductComponent,loadChildren:'./detail/detail.module#DetailModule'},
                {path:'item',loadChildren:'./detail/item/item.module#ItemModule'},
                {path:'item2',loadChildren:'./detail/item2/item2.module#Item2Module'},
                {path:'',component:i6.ProductComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9wcm9kdWN0Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3Byb2R1Y3QvcHJvZHVjdC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
