/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../app/app.module';
import * as i2 from '../../app/app.component';
import * as i3 from './chat/chat.component.ngfactory';
import * as i4 from './articles/articles.component.ngfactory';
import * as i5 from './articles/list/list.component.ngfactory';
import * as i6 from './articles/create/create.component.ngfactory';
import * as i7 from './articles/view/view.component.ngfactory';
import * as i8 from './articles/edit/edit.component.ngfactory';
import * as i9 from './authentication/authentication.component.ngfactory';
import * as i10 from './authentication/signin/signin.component.ngfactory';
import * as i11 from './authentication/signup/signup.component.ngfactory';
import * as i12 from './home/home.component.ngfactory';
import * as i13 from './route-study/route-study.component.ngfactory';
import * as i14 from './app.component.ngfactory';
import * as i15 from '@angular/common';
import * as i16 from '@angular/platform-browser';
import * as i17 from '@angular/http';
import * as i18 from '@angular/forms';
import * as i19 from '../../app/services/authentication.service';
import * as i20 from '../../app/services/articles.service';
import * as i21 from '../../app/chat/chat.service';
import * as i22 from '@angular/router';
import * as i23 from '../../app/authentication/logger.service';
import * as i24 from '../../app/coremodule/core.module';
import * as i25 from '../../app/chat/chat.component';
import * as i26 from '../../app/articles/articles.component';
import * as i27 from '../../app/articles/list/list.component';
import * as i28 from '../../app/articles/create/create.component';
import * as i29 from '../../app/articles/view/view.component';
import * as i30 from '../../app/articles/edit/edit.component';
import * as i31 from '../../app/authentication/authentication.component';
import * as i32 from '../../app/authentication/signin/signin.component';
import * as i33 from '../../app/authentication/signup/signup.component';
import * as i34 from '../../app/home/home.component';
import * as i35 from '../../app/route-study/route-study.component';
import * as i36 from '../../app/chat/chat-routing.module';
import * as i37 from '../../app/chat/chat.module';
import * as i38 from '../../app/articles/articles-routing.module';
import * as i39 from '../../app/articles/articles.module';
import * as i40 from '../../app/authentication/authentication-routing.module';
import * as i41 from '../../app/authentication/authentication.module';
import * as i42 from '../../app/home/home-routing.module';
import * as i43 from '../../app/home/home.module';
import * as i44 from '../../app/route-study/route-study-routing.module';
import * as i45 from '../../app/route-study/route-study.module';
import * as i46 from '../../app/app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.ChatComponentNgFactory,i4.ArticlesComponentNgFactory,i5.ListComponentNgFactory,
              i6.CreateComponentNgFactory,i7.ViewComponentNgFactory,i8.EditComponentNgFactory,
              i9.AuthenticationComponentNgFactory,i10.SigninComponentNgFactory,i11.SignupComponentNgFactory,
              i12.HomeComponentNgFactory,i13.RouteStudyComponentNgFactory,i14.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i15.NgLocalization,i15.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i16.DomSanitizer,i16.ɵe,[i15.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i16.DomSanitizer]),i0.ɵmpd(4608,
              i16.HAMMER_GESTURE_CONFIG,i16.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i16.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i16.ɵDomEventsPlugin(p0_0),new i16.ɵKeyEventsPlugin(p1_0),
                    new i16.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i15.DOCUMENT,i15.DOCUMENT,i15.DOCUMENT,i16.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i16.EventManager,i16.EventManager,[i16.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i16.ɵDomSharedStylesHost,i16.ɵDomSharedStylesHost,
              [i15.DOCUMENT]),i0.ɵmpd(4608,i16.ɵDomRendererFactory2,i16.ɵDomRendererFactory2,
              [i16.EventManager,i16.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,
              (null as any),[i16.ɵDomRendererFactory2]),i0.ɵmpd(6144,i16.ɵSharedStylesHost,
              (null as any),[i16.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,
              i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i16.Meta,i16.Meta,[i15.DOCUMENT]),
          i0.ɵmpd(4608,i16.Title,i16.Title,[i15.DOCUMENT]),i0.ɵmpd(4608,i17.BrowserXhr,
              i17.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i17.ResponseOptions,i17.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i17.XSRFStrategy,i17.ɵb,([] as any[])),i0.ɵmpd(4608,
              i17.XHRBackend,i17.XHRBackend,[i17.BrowserXhr,i17.ResponseOptions,i17.XSRFStrategy]),
          i0.ɵmpd(4608,i17.RequestOptions,i17.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i17.Http,i17.ɵc,[i17.XHRBackend,i17.RequestOptions]),i0.ɵmpd(4608,i18.ɵi,
              i18.ɵi,([] as any[])),i0.ɵmpd(4608,i19.AuthenticationService,i19.AuthenticationService,
              [i17.Http]),i0.ɵmpd(4608,i20.ArticlesService,i20.ArticlesService,[i17.Http]),
          i0.ɵmpd(4608,i21.ChatService,i21.ChatService,[i22.Router,i19.AuthenticationService]),
          i0.ɵmpd(4608,i23.LoggerService,i23.LoggerService,([] as any[])),i0.ɵmpd(5120,
              i22.ActivatedRoute,i22.ɵf,[i22.Router]),i0.ɵmpd(4608,i22.NoPreloading,
              i22.NoPreloading,([] as any[])),i0.ɵmpd(6144,i22.PreloadingStrategy,
              (null as any),[i22.NoPreloading]),i0.ɵmpd(135680,i22.RouterPreloader,
              i22.RouterPreloader,[i22.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i22.PreloadingStrategy]),i0.ɵmpd(4608,i22.PreloadAllModules,
              i22.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i22.ROUTER_INITIALIZER,
              i22.ɵi,[i22.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i22.ROUTER_INITIALIZER]),i0.ɵmpd(512,i15.CommonModule,i15.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i16.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i22.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i22.ɵg,i22.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i16.ɵc(p0_0,p0_1),i22.ɵh(p1_0)];
              },[[2,i16.NgProbeToken],[2,i0.NgProbeToken],i22.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i16.BrowserModule,i16.BrowserModule,[[3,i16.BrowserModule]]),
          i0.ɵmpd(512,i17.HttpModule,i17.HttpModule,([] as any[])),i0.ɵmpd(512,i18.ɵba,
              i18.ɵba,([] as any[])),i0.ɵmpd(512,i18.FormsModule,i18.FormsModule,([] as any[])),
          i0.ɵmpd(512,i24.CoreModule,i24.CoreModule,([] as any[])),i0.ɵmpd(1024,i22.ɵa,
              i22.ɵd,[[3,i22.Router]]),i0.ɵmpd(512,i22.UrlSerializer,i22.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i22.ChildrenOutletContexts,i22.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i22.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i15.LocationStrategy,i22.ɵc,[i15.PlatformLocation,[2,i15.APP_BASE_HREF],
              i22.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i15.Location,i15.Location,[i15.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i22.ROUTES,() => {
            return [[{path:'chat',component:i25.ChatComponent}],[{path:'articles',
                component:i26.ArticlesComponent,children:[{path:'',component:i27.ListComponent},
                    {path:'create',component:i28.CreateComponent},{path:':articleId',
                        component:i29.ViewComponent},{path:':articleId/edit',component:i30.EditComponent}]}],
                [{path:'authentication',component:i31.AuthenticationComponent,children:[{path:'signin',
                    component:i32.SigninComponent},{path:'signup',component:i33.SignupComponent}]}],
                [{path:'home',component:i34.HomeComponent}],[{path:'route-study',component:i35.RouteStudyComponent,
                    children:[{path:'rshome',loadChildren:'./rshome/rshome.module#RSHomeModule'},
                        {path:'product',loadChildren:'./product/product.module#ProductModule'}]}],
                [{path:'',redirectTo:'home',pathMatch:'full'}]];
          },([] as any[])),i0.ɵmpd(1024,i22.Router,i22.ɵe,[i0.ApplicationRef,i22.UrlSerializer,
              i22.ChildrenOutletContexts,i15.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i22.ROUTES,i22.ROUTER_CONFIGURATION,[2,i22.UrlHandlingStrategy],
              [2,i22.RouteReuseStrategy]]),i0.ɵmpd(512,i22.RouterModule,i22.RouterModule,
              [[2,i22.ɵa],[2,i22.Router]]),i0.ɵmpd(512,i36.ChatRoutingModule,i36.ChatRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i37.ChatModule,i37.ChatModule,([] as any[])),
          i0.ɵmpd(512,i38.ArticlesRoutingModule,i38.ArticlesRoutingModule,([] as any[])),
          i0.ɵmpd(512,i39.ArticlesModule,i39.ArticlesModule,([] as any[])),i0.ɵmpd(512,
              i40.AuthenticationRoutingModule,i40.AuthenticationRoutingModule,([] as any[])),
          i0.ɵmpd(512,i41.AuthenticationModule,i41.AuthenticationModule,([] as any[])),
          i0.ɵmpd(512,i42.HomeRoutingModule,i42.HomeRoutingModule,([] as any[])),i0.ɵmpd(512,
              i43.HomeModule,i43.HomeModule,([] as any[])),i0.ɵmpd(512,i44.RouteStudyRoutingModule,
              i44.RouteStudyRoutingModule,([] as any[])),i0.ɵmpd(512,i45.RouteStudyModule,
              i45.RouteStudyModule,([] as any[])),i0.ɵmpd(512,i46.AppRoutingModule,
              i46.AppRoutingModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
