/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.strong[_ngcontent-%COMP%] {\n    font-size: 1.5em;\n    font-weight: 100;\n}\n.highlight[_ngcontent-%COMP%] {\n    background-color:grey;\n}'];
//# sourceMappingURL=app.component.scss.shim.ngstyle.js.map