/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/home/home.module';
import * as i2 from './home.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/router';
import * as i5 from '../../../app/home/home-routing.module';
import * as i6 from '../../../app/home/home.component';
export const HomeModuleNgFactory:i0.NgModuleFactory<i1.HomeModule> = i0.ɵcmf(i1.HomeModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,
              i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i4.RouterModule,
              i4.RouterModule,[[2,i4.ɵa],[2,i4.Router]]),i0.ɵmpd(512,i5.HomeRoutingModule,
              i5.HomeRoutingModule,([] as any[])),i0.ɵmpd(512,i1.HomeModule,i1.HomeModule,
              ([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'home',component:i6.HomeComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvaG9tZS9ob21lLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL2hvbWUvaG9tZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
