/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i2 from '../../../app/chat/chat.component';
export declare const RenderType_ChatComponent: i0.RendererType2;
export declare function View_ChatComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_ChatComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ChatComponentNgFactory: i0.ComponentFactory<i2.ChatComponent>;
