/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/chat/chat.module';
import * as i2 from './chat.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from '../../../app/chat/chat.service';
import * as i6 from '@angular/router';
import * as i7 from '../../../app/services/authentication.service';
import * as i8 from '../../../app/chat/chat-routing.module';
import * as i9 from '../../../app/chat/chat.component';
export const ChatModuleNgFactory:i0.NgModuleFactory<i1.ChatModule> = i0.ɵcmf(i1.ChatModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ChatComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i5.ChatService,i5.ChatService,
              [i6.Router,i7.AuthenticationService]),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,
              i4.FormsModule,i4.FormsModule,([] as any[])),i0.ɵmpd(512,i6.RouterModule,
              i6.RouterModule,[[2,i6.ɵa],[2,i6.Router]]),i0.ɵmpd(512,i8.ChatRoutingModule,
              i8.ChatRoutingModule,([] as any[])),i0.ɵmpd(512,i1.ChatModule,i1.ChatModule,
              ([] as any[])),i0.ɵmpd(1024,i6.ROUTES,() => {
            return [[{path:'chat',component:i9.ChatComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvY2hhdC9jaGF0Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL2NoYXQvY2hhdC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
