/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../../app/route-study/product/list/list.component';
import * as i2 from '../../../../../app/route-study/product/test.service';
const styles_ListComponent:any[] = ([] as any[]);
export const RenderType_ListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ListComponent,data:{}});
export function View_ListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['The route is "product/list".'])),
      (_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(null as any));
}
export function View_ListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-product-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_ListComponent_0,
      RenderType_ListComponent)),i0.ɵdid(49152,(null as any),0,i1.ListComponent,[i2.TestService],
      (null as any),(null as any))],(null as any),(null as any));
}
export const ListComponentNgFactory:i0.ComponentFactory<i1.ListComponent> = i0.ɵccf('my-product-list',
    i1.ListComponent,View_ListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9saXN0L2xpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcHJvZHVjdC9saXN0L2xpc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9wcm9kdWN0L2xpc3QvbGlzdC5jb21wb25lbnQudHMuTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9wcm9kdWN0L2xpc3QvbGlzdC5jb21wb25lbnQudHMuTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXY+VGhlIHJvdXRlIGlzIFwicHJvZHVjdC9saXN0XCIuPC9kaXY+XG4gICIsIjxteS1wcm9kdWN0LWxpc3Q+PC9teS1wcm9kdWN0LWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDJDQUNJO01BQUE7TUFBQSw4QkFBSztNQUFrQzs7O29CQ0QzQztNQUFBOzhCQUFBLFVBQUE7TUFBQTs7OyJ9
