/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../../app/route-study/rshome/rshome.component';
const styles_RSHomeComponent:any[] = ([] as any[]);
export const RenderType_RSHomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_RSHomeComponent,data:{}});
export function View_RSHomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),
      (null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted((null as any),['The route is "rshome".'])),
      (_l()(),i0.ɵted((null as any),['\n  ']))],(null as any),(null as any));
}
export function View_RSHomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-home',([] as any[]),
      (null as any),(null as any),(null as any),View_RSHomeComponent_0,RenderType_RSHomeComponent)),
      i0.ɵdid(49152,(null as any),0,i1.RSHomeComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const RSHomeComponentNgFactory:i0.ComponentFactory<i1.RSHomeComponent> = i0.ɵccf('my-home',
    i1.RSHomeComponent,View_RSHomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcnNob21lL3JzaG9tZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9yb3V0ZS1zdHVkeS9yc2hvbWUvcnNob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvcm91dGUtc3R1ZHkvcnNob21lL3JzaG9tZS5jb21wb25lbnQudHMuUlNIb21lQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9hcHBsZS9Eb2N1bWVudHMveGl4aWppdV9uZy1tZC9tZWFuLXN0YWNrL2NsaWVudC1zcmMvYXBwL3JvdXRlLXN0dWR5L3JzaG9tZS9yc2hvbWUuY29tcG9uZW50LnRzLlJTSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXY+VGhlIHJvdXRlIGlzIFwicnNob21lXCIuPC9kaXY+XG4gICIsIjxteS1ob21lPjwvbXktaG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQSwyQ0FDSTtNQUFBO01BQUEsOEJBQUs7TUFBNEI7OztvQkNEckM7TUFBQTthQUFBO1VBQUE7OzsifQ==
