/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/articles/articles.module';
import * as i2 from './articles.component.ngfactory';
import * as i3 from './list/list.component.ngfactory';
import * as i4 from './create/create.component.ngfactory';
import * as i5 from './view/view.component.ngfactory';
import * as i6 from './edit/edit.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/forms';
import * as i9 from '@angular/router';
import * as i10 from '../../../app/articles/articles-routing.module';
import * as i11 from '../../../app/articles/articles.component';
import * as i12 from '../../../app/articles/list/list.component';
import * as i13 from '../../../app/articles/create/create.component';
import * as i14 from '../../../app/articles/view/view.component';
import * as i15 from '../../../app/articles/edit/edit.component';
export const ArticlesModuleNgFactory:i0.NgModuleFactory<i1.ArticlesModule> = i0.ɵcmf(i1.ArticlesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ArticlesComponentNgFactory,i3.ListComponentNgFactory,i4.CreateComponentNgFactory,
              i5.ViewComponentNgFactory,i6.EditComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i7.NgLocalization,i7.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i8.ɵi,i8.ɵi,([] as any[])),i0.ɵmpd(512,i7.CommonModule,
          i7.CommonModule,([] as any[])),i0.ɵmpd(512,i8.ɵba,i8.ɵba,([] as any[])),
          i0.ɵmpd(512,i8.FormsModule,i8.FormsModule,([] as any[])),i0.ɵmpd(512,i9.RouterModule,
              i9.RouterModule,[[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,i10.ArticlesRoutingModule,
              i10.ArticlesRoutingModule,([] as any[])),i0.ɵmpd(512,i1.ArticlesModule,
              i1.ArticlesModule,([] as any[])),i0.ɵmpd(1024,i9.ROUTES,() => {
            return [[{path:'articles',component:i11.ArticlesComponent,children:[{path:'',
                component:i12.ListComponent},{path:'create',component:i13.CreateComponent},
                {path:':articleId',component:i14.ViewComponent},{path:':articleId/edit',
                    component:i15.EditComponent}]}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXJ0aWNsZXMvYXJ0aWNsZXMubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXJ0aWNsZXMvYXJ0aWNsZXMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
