/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i2 from '../../../app/articles/articles.component';
export declare const RenderType_ArticlesComponent: i0.RendererType2;
export declare function View_ArticlesComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_ArticlesComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const ArticlesComponentNgFactory: i0.ComponentFactory<i2.ArticlesComponent>;
