/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/articles/articles-routing.module';
import * as i2 from './articles.component.ngfactory';
import * as i3 from './list/list.component.ngfactory';
import * as i4 from './create/create.component.ngfactory';
import * as i5 from './view/view.component.ngfactory';
import * as i6 from './edit/edit.component.ngfactory';
import * as i7 from '@angular/router';
import * as i8 from '../../../app/articles/articles.component';
import * as i9 from '../../../app/articles/list/list.component';
import * as i10 from '../../../app/articles/create/create.component';
import * as i11 from '../../../app/articles/view/view.component';
import * as i12 from '../../../app/articles/edit/edit.component';
export const ArticlesRoutingModuleNgFactory:i0.NgModuleFactory<i1.ArticlesRoutingModule> = i0.ɵcmf(i1.ArticlesRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ArticlesComponentNgFactory,i3.ListComponentNgFactory,i4.CreateComponentNgFactory,
              i5.ViewComponentNgFactory,i6.EditComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(512,i7.RouterModule,i7.RouterModule,[[2,i7.ɵa],
          [2,i7.Router]]),i0.ɵmpd(512,i1.ArticlesRoutingModule,i1.ArticlesRoutingModule,
          ([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
        return [[{path:'articles',component:i8.ArticlesComponent,children:[{path:'',
            component:i9.ListComponent},{path:'create',component:i10.CreateComponent},
            {path:':articleId',component:i11.ViewComponent},{path:':articleId/edit',
                component:i12.EditComponent}]}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXJ0aWNsZXMvYXJ0aWNsZXMtcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9hcnRpY2xlcy9hcnRpY2xlcy1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
