/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '../../../app/articles/articles.component';
import * as i3 from '../../../app/services/articles.service';
const styles_ArticlesComponent:any[] = ([] as any[]);
export const RenderType_ArticlesComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ArticlesComponent,data:{}});
export function View_ArticlesComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export function View_ArticlesComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'articles',([] as any[]),
      (null as any),(null as any),(null as any),View_ArticlesComponent_0,RenderType_ArticlesComponent)),
      i0.ɵdid(49152,(null as any),0,i2.ArticlesComponent,[i3.ArticlesService],(null as any),
          (null as any))],(null as any),(null as any));
}
export const ArticlesComponentNgFactory:i0.ComponentFactory<i2.ArticlesComponent> = i0.ɵccf('articles',
    i2.ArticlesComponent,View_ArticlesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXJ0aWNsZXMvYXJ0aWNsZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXJ0aWNsZXMvYXJ0aWNsZXMuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYXBwbGUvRG9jdW1lbnRzL3hpeGlqaXVfbmctbWQvbWVhbi1zdGFjay9jbGllbnQtc3JjL2FwcC9hcnRpY2xlcy9hcnRpY2xlcy5jb21wb25lbnQudHMuQXJ0aWNsZXNDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FwcGxlL0RvY3VtZW50cy94aXhpaml1X25nLW1kL21lYW4tc3RhY2svY2xpZW50LXNyYy9hcHAvYXJ0aWNsZXMvYXJ0aWNsZXMuY29tcG9uZW50LnRzLkFydGljbGVzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PiIsIjxhcnRpY2xlcz48L2FydGljbGVzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO3NDQUFBO1VBQUE7SUFBQTs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
