/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i1 from '../../../../app/authentication/signin/signin.component';
export declare const RenderType_SigninComponent: i0.RendererType2;
export declare function View_SigninComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_SigninComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const SigninComponentNgFactory: i0.ComponentFactory<i1.SigninComponent>;
